#ifndef WIDGETS_H
#define WIDGETS_H
#include <QDialog>
#include <QMainWindow>
#include <QCoreApplication>
#include <QActionGroup>
#include <QObject>
#include <QSystemTrayIcon>
#include <QPushButton>
#include <QTime>
#include <QDateTime>
#include <QTimer>
#include <QLabel>
#include <QGridLayout>
#include <QWidget>
#include <QMenuBar>
#include <QMenu>
#include <QEvent>
#include <QCloseEvent>
#include <QPixmap>
#include <QLineEdit>
#include <QComboBox>
#include <QRadioButton>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QJsonParseError>
#include <QTableWidget>
#include <QHelpEngineCore>
#include <QHelpLink>
#include <QTextBrowser>
#include <QHelpFilterEngine>
#include <QMessageBox>

#endif // WIDGETS_H
